import type { Metadata } from "next";
import { Open_Sans} from "next/font/google";
import "../globals.css";

const openSans = Open_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${openSans.className} font-normal`}>
      <div>Login</div>
        {children}
      </body>
    </html>
  );
}
